import type { Metadata } from 'next';
import { Gelasio } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/navBar/navBar';
import Footer from '@/components/footer/footer';

const gelasio = Gelasio({
  variable: '--font-gelasio',
  subsets: ['latin'],
  weight: ['700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gelasio.variable} antialiased`}>
        <NavBar />
        <div className="snowBg">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
